// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementSystem.Data;

#nullable disable

namespace ProductManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241231125437_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementSystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 31, 12, 54, 37, 347, DateTimeKind.Utc).AddTicks(5809),
                            Description = "Wireless headphones with noise-canceling technology for a high-quality listening experience.",
                            ImageUrl = "https://images-cdn.ubuy.co.in/64cbbee91a56505f2c3a830e-bose-quietcomfort-45-headphones-noise.jpg",
                            Name = "Bose QuietComfort 45",
                            Price = 329.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 31, 12, 54, 37, 347, DateTimeKind.Utc).AddTicks(6894),
                            Description = "Smartwatch with advanced health features and always-on display, compatible with iPhone.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71sLCEpm9aL._AC_SL1500_.jpg",
                            Name = "Apple Watch Series 9",
                            Price = 399.99000000000001
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 12, 31, 12, 54, 37, 347, DateTimeKind.Utc).AddTicks(6896),
                            Description = "High-quality coffee maker with strong brew, iced coffee, and programmable settings.",
                            ImageUrl = "https://i.insider.com/64d2495620f1cf0019ccf203?width=700",
                            Name = "Keurig K-Elite Coffee Maker",
                            Price = 129.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 12, 31, 12, 54, 37, 347, DateTimeKind.Utc).AddTicks(6897),
                            Description = "Next-generation gaming console with high-speed SSD and immersive gameplay.",
                            ImageUrl = "https://gmedia.playstation.com/is/image/SIEPDC/ps5-pro-dualsense-image-block-01-en-16aug24?$facebook$",
                            Name = "PlayStation 5",
                            Price = 499.99000000000001
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 12, 31, 12, 54, 37, 347, DateTimeKind.Utc).AddTicks(6897),
                            Description = "Electric scooter with long battery life and powerful motor, ideal for city commuting.",
                            ImageUrl = "https://xprs.s3.eu-west-3.amazonaws.com/media/product_images/Screen_Shot_2023-02-02_at_3.20.36_PM.png",
                            Name = "Xiaomi Mi Electric Scooter Pro 2",
                            Price = 499.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
